In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [5]:
df=pd.read_csv('Resume.csv')

In [6]:
df.head()

,ID,Resume_str,Resume_html,Category
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,"<div class=""fontsize fontface vmargins hmargin...",HR
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...","<div class=""fontsize fontface vmargins hmargin...",HR
2,33176873,HR DIRECTOR Summary Over 2...,"<div class=""fontsize fontface vmargins hmargin...",HR
3,27018550,HR SPECIALIST Summary Dedica...,"<div class=""fontsize fontface vmargins hmargin...",HR
4,17812897,HR MANAGER Skill Highlights ...,"<div class=""fontsize fontface vmargins hmargin...",HR

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2484 entries, 0 to 2483
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           2484 non-null   int64
 1   Resume_str   2484 non-null   str
 2   Resume_html  2484 non-null   str
 3   Category     2484 non-null   str
dtypes: int64(1), str(3)
memory usage: 52.3 MB

In [8]:
print("Number of Rows :", df.shape[0])
print("Number of Columns :", df.shape[1])

Number of Rows : 2484
Number of Columns : 4

In [9]:
df.columns

Index(['ID', 'Resume_str', 'Resume_html', 'Category'], dtype='str')

In [10]:
df.isnull().sum()

ID             0
Resume_str     0
Resume_html    0
Category       0
dtype: int64

In [11]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

In [12]:
df = df.drop_duplicates()

In [13]:
df.drop(columns=["Resume_html"], inplace=True)

In [14]:
df.rename(columns={
    "Resume_str": "Resume"
}, inplace=True)

In [15]:
df.dtypes

ID          int64
Resume        str
Category      str
dtype: object

In [18]:
print("Total Categories :", df["Category"].nunique())

Total Categories : 24

In [19]:
print(df["Category"].unique())

<ArrowStringArray>
[                    'HR',               'DESIGNER', 'INFORMATION-TECHNOLOGY',
                'TEACHER',               'ADVOCATE',   'BUSINESS-DEVELOPMENT',
             'HEALTHCARE',                'FITNESS',            'AGRICULTURE',
                    'BPO',                  'SALES',             'CONSULTANT',
          'DIGITAL-MEDIA',             'AUTOMOBILE',                   'CHEF',
                'FINANCE',                'APPAREL',            'ENGINEERING',
             'ACCOUNTANT',           'CONSTRUCTION',       'PUBLIC-RELATIONS',
                'BANKING',                   'ARTS',               'AVIATION']
Length: 24, dtype: str

In [20]:
df["Resume_Length"] = df["Resume"].apply(len)

In [21]:
df.head()

,ID,Resume,Category,Resume_Length
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,HR,5442
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...",HR,5572
2,33176873,HR DIRECTOR Summary Over 2...,HR,7720
3,27018550,HR SPECIALIST Summary Dedica...,HR,2855
4,17812897,HR MANAGER Skill Highlights ...,HR,9172

In [22]:
df.to_csv("clean_resume.csv", index=False)