In [3]:
import pandas as pd
import pickle

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
df=pd.read_csv('clean_resume.csv')

In [5]:
df.head()

,ID,Resume,Category,Resume_Length
0,16852973,HR ADMINISTRATOR/MARKETING ASSOCIATE\...,HR,5442
1,22323967,"HR SPECIALIST, US HR OPERATIONS ...",HR,5572
2,33176873,HR DIRECTOR Summary Over 2...,HR,7720
3,27018550,HR SPECIALIST Summary Dedica...,HR,2855
4,17812897,HR MANAGER Skill Highlights ...,HR,9172

In [9]:
print(df.columns)

Index(['ID', 'Resume', 'Category', 'Resume_Length'], dtype='str')

In [12]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^a-zA-Z ]', ' ', text)
    text = re.sub(r'\s+', ' ', text)
    return text

df["Clean_Resume"] = df["Resume"].apply(clean_text)

In [13]:
tfidf = TfidfVectorizer(stop_words="english")

tfidf_matrix = tfidf.fit_transform(df["Clean_Resume"])

In [14]:
print(df.columns)

Index(['ID', 'Resume', 'Category', 'Resume_Length', 'Clean_Resume'], dtype='str')

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')

tfidf_matrix = tfidf.fit_transform(df["Clean_Resume"])

In [16]:
pickle.dump(tfidf, open("tfidf.pkl", "wb"))
pickle.dump(df, open("resume_data.pkl", "wb"))

print("Model Saved Successfully!")

Model Saved Successfully!

In [17]:
def recommend_jobs(resume_text):

    # Convert input resume into TF-IDF vector
    resume_vector = tfidf.transform([resume_text])

    # Calculate similarity with all resumes
    scores = cosine_similarity(resume_vector, tfidf_matrix)

    # Get top 5 similar resumes
    top_index = scores.argsort()[0][-5:][::-1]

    # Return recommended categories
    return df.iloc[top_index][["Category"]]

In [18]:
sample_resume = """
Python
Machine Learning
SQL
Data Analysis
"""

recommend_jobs(sample_resume)

         Category
1762  ENGINEERING
1218   CONSULTANT
1142   CONSULTANT
2153      BANKING
1339   AUTOMOBILE